<?php

namespace Database\Seeders;

use App\Models\Blog;
use App\Models\Page;
use App\Models\Stock;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'title' => 'Запись блога 1',
                'h1_title' => 'Запись блога 1',
                'description' => 'Описание акции 1',
                'description_header' => 'Описание акции 1',
                'content' => 'Описание акции 1',
                'slug' => 'blog-single-1',
                'og_title' => 'Запись блога 1',
                'og_description' => 'Описание акции 1',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-1',
                'meta_title' => 'Запись блога 1',
                'meta_description' => 'Описание акции 1',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 2',
                'h1_title' => 'Запись блога 2',
                'description' => 'Описание акции 2',
                'description_header' => 'Описание акции 2',
                'content' => 'Описание акции 2',
                'slug' => 'blog-single-2',
                'og_title' => 'Запись блога 2',
                'og_description' => 'Описание акции 2',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-2',
                'meta_title' => 'Запись блога 2',
                'meta_description' => 'Описание акции 2',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 3',
                'h1_title' => 'Запись блога 3',
                'description' => 'Описание акции 3',
                'description_header' => 'Описание акции 3',
                'content' => 'Описание акции 3',
                'slug' => 'blog-single-3',
                'og_title' => 'Запись блога 3',
                'og_description' => 'Описание акции 3',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-3',
                'meta_title' => 'Запись блога 3',
                'meta_description' => 'Описание акции 3',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 4',
                'h1_title' => 'Запись блога 4',
                'description' => 'Описание акции 4',
                'description_header' => 'Описание акции 4',
                'content' => 'Описание акции 4',
                'slug' => 'blog-single-4',
                'og_title' => 'Запись блога 4',
                'og_description' => 'Описание акции 4',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-4',
                'meta_title' => 'Запись блога 4',
                'meta_description' => 'Описание акции 4',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 5',
                'h1_title' => 'Запись блога 5',
                'description' => 'Описание акции 5',
                'description_header' => 'Описание акции 5',
                'content' => 'Описание акции 5',
                'slug' => 'blog-single-5',
                'og_title' => 'Запись блога 5',
                'og_description' => 'Описание акции 5',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-5',
                'meta_title' => 'Запись блога 5',
                'meta_description' => 'Описание акции 5',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 6',
                'h1_title' => 'Запись блога 6',
                'description' => 'Описание акции 6',
                'description_header' => 'Описание акции 6',
                'content' => 'Описание акции 6',
                'slug' => 'blog-single-6',
                'og_title' => 'Запись блога 6',
                'og_description' => 'Описание акции 6',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-6',
                'meta_title' => 'Запись блога 6',
                'meta_description' => 'Описание акции 6',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 7',
                'h1_title' => 'Запись блога 7',
                'description' => 'Описание акции 7',
                'description_header' => 'Описание акции 7',
                'content' => 'Описание акции 7',
                'slug' => 'blog-single-7',
                'og_title' => 'Запись блога 7',
                'og_description' => 'Описание акции 7',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-7',
                'meta_title' => 'Запись блога 7',
                'meta_description' => 'Описание акции 7',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 8',
                'h1_title' => 'Запись блога 8',
                'description' => 'Описание акции 8',
                'description_header' => 'Описание акции 8',
                'content' => 'Описание акции 8',
                'slug' => 'blog-single-8',
                'og_title' => 'Запись блога 8',
                'og_description' => 'Описание акции 8',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-8',
                'meta_title' => 'Запись блога 8',
                'meta_description' => 'Описание акции 8',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 9',
                'h1_title' => 'Запись блога 9',
                'description' => 'Описание акции 9',
                'description_header' => 'Описание акции 9',
                'content' => 'Описание акции 9',
                'slug' => 'blog-single-9',
                'og_title' => 'Запись блога 9',
                'og_description' => 'Описание акции 9',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-9',
                'meta_title' => 'Запись блога 9',
                'meta_description' => 'Описание акции 9',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 10',
                'h1_title' => 'Запись блога 10',
                'description' => 'Описание акции 10',
                'description_header' => 'Описание акции 10',
                'content' => 'Описание акции 10',
                'slug' => 'blog-single-10',
                'og_title' => 'Запись блога 10',
                'og_description' => 'Описание акции 10',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-10',
                'meta_title' => 'Запись блога 10',
                'meta_description' => 'Описание акции 10',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 11',
                'h1_title' => 'Запись блога 11',
                'description' => 'Описание акции 11',
                'description_header' => 'Описание акции 11',
                'content' => 'Описание акции 11',
                'slug' => 'blog-single-11',
                'og_title' => 'Запись блога 11',
                'og_description' => 'Описание акции 11',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-11',
                'meta_title' => 'Запись блога 11',
                'meta_description' => 'Описание акции 11',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 12',
                'h1_title' => 'Запись блога 12',
                'description' => 'Описание акции 12',
                'description_header' => 'Описание акции 12',
                'content' => 'Описание акции 12',
                'slug' => 'blog-single-12',
                'og_title' => 'Запись блога 12',
                'og_description' => 'Описание акции 12',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-12',
                'meta_title' => 'Запись блога 12',
                'meta_description' => 'Описание акции 12',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 13',
                'h1_title' => 'Запись блога 13',
                'description' => 'Описание акции 13',
                'description_header' => 'Описание акции 13',
                'content' => 'Описание акции 13',
                'slug' => 'blog-single-13',
                'og_title' => 'Запись блога 13',
                'og_description' => 'Описание акции 13',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-13',
                'meta_title' => 'Запись блога 13',
                'meta_description' => 'Описание акции 13',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 14',
                'h1_title' => 'Запись блога 14',
                'description' => 'Описание акции 14',
                'description_header' => 'Описание акции 14',
                'content' => 'Описание акции 14',
                'slug' => 'blog-single-14',
                'og_title' => 'Запись блога 14',
                'og_description' => 'Описание акции 14',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-14',
                'meta_title' => 'Запись блога 14',
                'meta_description' => 'Описание акции 14',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            [
                'title' => 'Запись блога 15',
                'h1_title' => 'Запись блога 15',
                'description' => 'Описание акции 15',
                'description_header' => 'Описание акции 15',
                'content' => 'Описание акции 15',
                'slug' => 'blog-single-15',
                'og_title' => 'Запись блога 15',
                'og_description' => 'Описание акции 15',
                'og_url' => 'https://dr-malkov.ru/blog/blog-single-15',
                'meta_title' => 'Запись блога 15',
                'meta_description' => 'Описание акции 15',
                'meta_keywords' => 'Запись блога',

                'reading_time' => '1 минута',                'image' => 'img/stock-slider/1.jpg',
                'image_mob' => 'img/stock-slider/1.jpg',
            ],
            ];

        foreach ($data as $key => $value) {
            Blog::create($value);
        }
    }
}
